### ISSUE TITLE
text is white

### ISSUE THREAD

**Issue by redmangospros** [SwiftSites/Burst#1]
(contact)
(about)
etc.

**Comment by GreenBayRules** [comment]
Thats the whole point

**Comment by redmangospros** [comment]
But, you can't see iit

**Comment by GreenBayRules** [comment]
![image](https://user-images.githubusercontent.com/11379161/34361804-7f1d6b02-ea22-11e7-8c04-2d95dd7b526d.png)

**Comment by redmangospros** [comment]
It's fixed now! Yay!

**Comment by redmangospros** [comment]
![screenshot 2017-12-26 at 12 53 41 pm](https://user-images.githubusercontent.com/21000033/34361830-eb504948-ea3b-11e7-9c85-b9e2e8d87bd0.png)
